import {
  Building2,
  Crown,
  LayoutDashboard,
  ShieldCheck,
  Users,
} from "lucide-react";

export const roles = [
  {
    name: "Platform Super Admin",
    route: "/dashboard/admin",
    layer: "Platform governance + tenant operations",
    description: "Ecosystem-wide governance for organizations, tenant provisioning, AI systems, global courses, analytics, and white-label readiness.",
    inviteOnly: true,
    icon: LayoutDashboard,
  },
  {
    name: "Cell Leader / Assistant HOD",
    route: "/dashboard/leader",
    layer: "Personal learning + responsibility signals",
    description: "Personal learning, growth profile, assessments, certificates, activity, and readiness signals.",
    inviteOnly: false,
    icon: Users,
  },
  {
    name: "Zonal Leader / HOD",
    route: "/dashboard/community",
    layer: "Personal learning + team oversight",
    description: "Learning growth with zonal reporting, readiness signals, and leader development actions.",
    inviteOnly: false,
    icon: Users,
  },
  {
    name: "Community Leader",
    route: "/dashboard/community",
    layer: "Personal learning + community oversight",
    description: "Learning growth with community-level participation, leader maturity, and follow-up intelligence.",
    inviteOnly: false,
    icon: Users,
  },
  {
    name: "Area Leader",
    route: "/dashboard/community",
    layer: "Personal learning + area oversight",
    description: "Learning growth with area-level leadership health, readiness, and ministry participation signals.",
    inviteOnly: false,
    icon: Users,
  },
  {
    name: "District Pastor / Pastoral Leader",
    route: "/dashboard/directional",
    layer: "Personal learning + district oversight",
    description: "Learning growth with pastoral oversight, district health, and leader development intelligence.",
    inviteOnly: false,
    icon: ShieldCheck,
  },
  {
    name: "Directional Leader",
    route: "/dashboard/directional",
    layer: "Personal learning + directional oversight",
    description: "Learning growth with directional oversight, pastoral reporting, and leadership pipeline intelligence.",
    inviteOnly: false,
    icon: Crown,
  },
  {
    name: "Campus Pastor",
    route: "/dashboard/campus",
    layer: "Personal learning + campus oversight",
    description: "Personal learning with campus participation, inactive leaders, engagement, mentorship, and ministry-team performance.",
    inviteOnly: true,
    icon: Building2,
  },
  {
    name: "Sub-Group Pastor",
    route: "/dashboard/subgroup",
    layer: "Personal learning + subgroup oversight",
    description: "Personal learning with subgroup health, campus comparisons, leadership performance, and campus participation trends.",
    inviteOnly: true,
    icon: ShieldCheck,
  },
  {
    name: "Group Pastor",
    route: "/dashboard/group",
    layer: "Personal learning + group oversight",
    description: "Personal learning with strategic ministry intelligence, subgroup analytics, leadership pipeline visibility, and campus growth signals.",
    inviteOnly: true,
    icon: Crown,
  },
  {
    name: "Campus Admin",
    route: "/dashboard/campus-admin",
    layer: "Campus operations + analytics",
    description: "Campus-level operations, enrollment management, reporting, and learning analytics.",
    inviteOnly: true,
    icon: Building2,
  },
  {
    name: "Super Admin",
    route: "/dashboard/admin",
    layer: "Legacy platform administration",
    description: "Legacy global administration role that now resolves into Platform Super Admin access.",
    inviteOnly: true,
    icon: LayoutDashboard,
  },
];
